// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA01_sGx55DhTukfch938-r1wbKX8-PcVw',
    appId: '1:218375098784:web:77833eab3613463abb14c5',
    messagingSenderId: '218375098784',
    projectId: 'byteburst-d14d3',
    authDomain: 'byteburst-d14d3.firebaseapp.com',
    storageBucket: 'byteburst-d14d3.appspot.com',
    measurementId: 'G-Y4XYL0CVPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSOTz6dw5_SBOAWMkgKCAqbcOUwM2FeE4',
    appId: '1:218375098784:android:bc641138e1112d1fbb14c5',
    messagingSenderId: '218375098784',
    projectId: 'byteburst-d14d3',
    storageBucket: 'byteburst-d14d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7nsc2S98RP9mdOvukv1Qx46oPL2oloTo',
    appId: '1:218375098784:ios:fbc63bdecb9c2657bb14c5',
    messagingSenderId: '218375098784',
    projectId: 'byteburst-d14d3',
    storageBucket: 'byteburst-d14d3.appspot.com',
    iosBundleId: 'com.example.utmfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7nsc2S98RP9mdOvukv1Qx46oPL2oloTo',
    appId: '1:218375098784:ios:fbc63bdecb9c2657bb14c5',
    messagingSenderId: '218375098784',
    projectId: 'byteburst-d14d3',
    storageBucket: 'byteburst-d14d3.appspot.com',
    iosBundleId: 'com.example.utmfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA01_sGx55DhTukfch938-r1wbKX8-PcVw',
    appId: '1:218375098784:web:b10fb42b4965c5a2bb14c5',
    messagingSenderId: '218375098784',
    projectId: 'byteburst-d14d3',
    authDomain: 'byteburst-d14d3.firebaseapp.com',
    storageBucket: 'byteburst-d14d3.appspot.com',
    measurementId: 'G-8GW2CC9HY9',
  );
}
